export const headersClientsTable = [
  { label: "Ruta", field: "ruta" },
  { label: "Distribuidor", field: "rutaID" },
  { label: "Id interno", field: "clienteID" },
  { label: "Id sucursal", field: "sucursal" },
  { label: "Cliente", field: "nombreCliente" },
  { label: "Provincia", field: "provincia" },
  { label: "Distrito", field: "distrito" },
  { label: "Corregimiento", field: "corregimiento" },
  { label: "Dirección", field: "direccionCliente" },
  { label: "Tipo de negocio", field: "tipoNegocio" },
  { label: "Fif nuesto", field: "precio" },
  { label: "Fif otros", field: "precioAdd" },
  { label: "Acciones", field: "actions" },
];
