export const headersCustomersTable = [
  { label: "Id", field: "customerId" },
  { label: "Ruta", field: "route.name" },
  { label: "Código", field: "code" },
  { label: "Nombre", field: "name" },
  { label: "Apellido", field: "lastName" },
  { label: "Tarjeta identificación", field: "identityCard" },
  { label: "Dirección", field: "address" },
  { label: "Teléfono", field: "houseNumber" },
  { label: "Latitud", field: "latitude" },
  { label: "Longitud", field: "longitude" },
  { label: "Contacto", field: "contactName" },
  { label: "Celular", field: "phone" },
  { label: "Correo", field: "email" },
  { label: "Dv", field: "dv" },
  { label: "Tipo de cliente", field: "customerType.name" },
  { label: "Provincia", field: "province.name" },
  { label: "Distrito", field: "district.name" },
  { label: "Corregimiento", field: "township.name" },
  { label: "Lugar poblado", field: "village.name" },
  { label: "Tipo de impusto", field: "taxpayerType.name" },
  { label: "Estado", field: "active" },
  { label: "Acciones", field: "actions" },
];