export const headersFrecuencyTable = [
  { label: "Id", field: "customerFrequencyId" },
  { label: "Cliente", field: "customer.name" },
  { label: "Frecuencia", field: "frequency" },
  { label: "Última visita", field: "lasstVisit" },
  { label: "Próxima visita", field: "nextVisit" },
  { label: "Observaciones", field: "observations" },
  { label: "L", field: "monday" },
  { label: "M", field: "tuesday" },
  { label: "Mi", field: "wednesday" },
  { label: "J", field: "thursday" },
  { label: "V", field: "friday" },
  { label: "S", field: "saturday" },
  { label: "D", field: "sunday" },
  { label: "Editar", field: "actions" },
];