export const headersDevicesTable = [
  { label: "Id interno", field: "posId" },
  { label: "Sucursal", field: "branchOffice.branchOfficeName" },
  { label: "Id del dispositivo", field: "deviceId" },
  { label: "dPtoFacDF", field: "dPtoFacDF" },
  { label: "Prefijo de factura", field: "invoicePrefix" },
  { label: "Secuencial de factura", field: "invoiceSequential" },
  { label: "Nº de copia de factura", field: "invoiceNumberCopies" },
  { label: "Nº de cierre de factura", field: "invoiceNumberClosings" },
  { label: "Secuencial de factura electrónica", field: "eInvoiceSequential" },
  { label: "Prefijo de crédito", field: "creditPrefix" },
  { label: "Secuencial de crédito", field: "creditSequential" },
  { label: "Impresor", field: "printer" },
  { label: "Factura en línea", field: "invoiceOnline" },
  { label: "Transporte", field: "freight" },
  { label: "Estado", field: "active" },
  { label: "Acciones", field: "actions" },
];
